sudo: required
services:
  - docker

before_install:
  - docker build -t astelware/multi-docker-aws-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true astelware/multi-docker-aws-react-test npm test -- --coverage

after_success:
  - docker build -t astelware/multi-docker-client ./client
  - docker build -t astelware/multi-docker-nginx ./nginx
  - docker build -t astelware/multi-docker-server ./server
  - docker build -t astelware/multi-docker-worker ./worker
  # Log in to the docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images to git hub
  - docker push astelware/multi-docker-client
  - docker push astelware/multi-docker-nginx
  - docker push astelware/multi-docker-server
  - docker push astelware/multi-docker-worker
